### ISSUE TITLE
Performance: Many App calls (whilst SpaceSummary could also do the trick)

### ISSUE THREAD

**Issue by eloo** [promregator/promregator#74] opened 2018-09-24 12:27 UTC
Hi,
related to #67 we have started to monitor promregator a little bit and we found some interesting statistics.
For example the huge amout of App calls
We are facing for example the following distribution of calls:
```
promregator_cffetch_latency_count{request_type="allApps"}  | 48168
promregator_cffetch_latency_count{request_type="app"}  | 714556
promregator_cffetch_latency_count{request_type="org"} | 14
promregator_cffetch_latency_count{request_type="space"}  | 84
promregator_cffetch_latency_count{request_type="spaceSummary"} | 146410
```
We have the following cache timout settings:
```
  cache:
    timeout:
      org: 86400        # Renew org cache every day (default: 3600)
      space: 43200      # Renew space cache twice a day (default: 3600)
      application: 15   # Renew app cache every 15s (default: 300)
      resolver:  60     # Renew target to CF (e.g. AllApps or regex) (default: 300)
```
With 18 Apps and 30 Instances monitored covered over a time of ~14 days.
We have a average of 35-40 app calls per minute.

So now the question:
For me this looks like a very huge amount of app requests and for me it looks like we are not gathering "new" information from the app call itself. 
So is it really neccessary to have that much app calls? because for me it looks like the space Summary is also containing all the needed data? 

Maybe @eaglerainbow you can give some insight?

Thx

**Comment by eaglerainbow** [comment] 2018-09-24 20:07
Well, I think your `cf.cache.timeout.application` and `cf.cache.timeout.resolver` values are really aggressive:

* It seems like that you have three spaces configured.
* For each of these spaces you are requesting that every minute the `allApps` request shall be sent (to resolve the regex)
* During that activity, also the content of all apps is put into the app's cache. However, please note that this only done every minute! And note that this only affects the `app` cache - not the `spaceSummary` cache.
* Already after 15 seconds, you declare the app's cache to be invalid (`cf.cache.timeout.application`). That means with the next scraping request (for the sake of simplicity I assume that your scraping interval is 15s), the entire cache is already gone again. Promregator still knows the guid of the apps, that's why it fires the app request. For each app it retrieves, it then cross-checks in which space it is, and tries to fetch the additional route/domain information via the `spaceSummary` request. It automatically aggregates on "per space level" internally. That's why the number of requests on `spaceSummary` is lower than on `app` level.
* The next time the scraping requests gets in, again all your app's cache is invalidated again. The `spaceSummary`'s cache has the same fast invalidation cycle as the `app`'s cache, as the `spaceSummary`'s cache contains data, which is dependent on the `app` cache's content.
* On the third iteration, still the very same happens: both the `app`'s and the `spaceSummary`'s cache is already invalidated again and needs to be refilled.
* Only at the fourth iteration, you are getting support an `allApps` resolution and at least your `app` cache will be filled again. The `spaceSummary`'s cache, though, is again invalidated and needs to be refetched. 

In a nutshell you could say that your aggressive setting of `cf.cache.timeout.application = 15` mainly means that with each scraping request of Prometheus, you are forcing to re-fetch the metadata from the Cloud Controller - more or less, the setting "disables" the app cache more or less (I would expect that if you had set `cf.cache.timeout.application = 1`, you would have seen almost the same values). 

Is metadata latency (routes, number of instances, ...) really such a big problem for you on monitoring that you have to set such aggressive cache timings?

There is one thing, though, with which you are right: We could have a look, if we can make more out of the `spaceSummary` requests (or fire the `spaceSummary` request earlier or even perhaps instead of an app request). I don't know whether this is a bright idea or not, as the number of `spaceSummary` requests could increase - and the latter is much more expensive than the simple `app` request...

**Comment by eloo** [comment] 2018-09-25 11:04
@eaglerainbow yes i'm using single endpoint scraping.
and yes we want to know changes to number of instances fast.. so maybe we could go for 30s but i guess all above would be too high.

and yes.. 3 spaces and 15s scrape interval

**Comment by eaglerainbow** [comment] 2018-09-25 17:02
@eloo: This isn't good news. Does this stay like this if you simply restart Promregator/the container?

**Comment by eaglerainbow** [comment] 2018-09-25 19:47
@eloo: I think I got it handled that with 7cdf93c and  f7e92de the `request_type="app"` calls are removed entirely. Instead Promregator reads the data completely from the `request_type="spaceSummary"` requests. In some edge cases, this might have some minor disadvantages, but I consider them mostly academic. In your case (with the very tough cache timing on application level), this may mean that we call the spaceSummary a little more often, but for that all the app's calls are gone. 

I have released `0.5.0-rc5` for you for testing.

**Comment by eloo** [comment] 2018-09-26 06:44
@eaglerainbow okay im testing rc5 now..
but it looks like non-regex apps are not discovered anymore..
in my config i have a couple of apps configured using regex which are shown but my two apps without regex are not shown.. 
any ideas for a reason for that? :D

**Comment by eaglerainbow** [comment] 2018-09-26 18:43
> but it looks like non-regex apps are not discovered anymore..

❓ :exclamation: :open_mouth: I'll have a look in a couple of minutes and will report back.

**Comment by eaglerainbow** [comment] 2018-09-26 18:51
Manual testing:
- [x] `application.yaml` with only non-regex application name 
- [x] `application.yaml` with only regex application name 
- [x] `application.yaml` with one non-regex and one regex application name

All tests ok for me.

**Comment by eaglerainbow** [comment] 2018-09-26 18:57
@eloo: Sorry, but I am currently not able to reproduce the issue with what I have at hand. For my configuration, both non-regex and regex applications work just fine. And browsing through the source code, I could find an obvious reason for this. Moreover, the unit test at https://github.com/promregator/promregator/blob/767cad34f701414bc4198b2abb1d3f62bd206cc8/src/test/java/org/cloudfoundry/promregator/scanner/ReactiveTargetResolverTest.java#L40 should cover an obvious error for your scenario.

Are you able to narrow this down a little more or give me something like a pattern that you have in your configuration for with which I could check more thoroughly?

Thanks!

**Comment by eaglerainbow** [comment] 2018-09-26 19:01
NB: just detected another problem during my test activities, which I have raised with #75

**Comment by eaglerainbow** [comment] 2018-09-27 07:40
> it looks like org and app name are now case sensitive :D

Ok, thanks for tracking that down. 
I wasn't aware that it had been case-insensitive before at all - I never had planned for this. Regex handling anyway will be case-sensitive, so that should be the way to go. 
Still, I don't like what you found, as the change may feel incompatible to consumers. That can easily be a trap when doing the update. At least we should add some more documentation on this and add it to the release note.

**Comment by eaglerainbow** [comment] 2018-09-27 07:57
There is more behind than just this. I have raised #76 to follow up on this.

**Comment by eaglerainbow** [comment] 2018-09-27 10:33
> it looks like org and app name are now case sensitive :D
> that wasn't the case before.. 

In the end, you convinced me that this isn't a great idea. I have changed this now. The coding change will be available with `0.5.0-rc6` (and later) - not released yet.

**Comment by eaglerainbow** [comment] 2018-09-27 10:51
Just for the record: Waiting for feedback from @eloo that performance metrics (esp. on `app`) are better now. If that is the case, from my side we should close the issue.

**Comment by eaglerainbow** [comment] 2018-11-21 20:18
> for me we could close this.. i guess the remove of the app calls was the best improvement for now

Okay, thanks for the feedback! 
With that feedback, please expect that I will release 0.5.0 (official) soon (perhaps this weekend). I will then close this issue by then.

**Comment by eaglerainbow** [comment] 2018-11-24 12:15
[0.5.0](https://github.com/promregator/promregator/releases/tag/v0.5.0) is out now. Happy usage 😁

**Closed by eaglerainbow** 2018-11-24 12:15 UTC
Labels: awaiting feedback, enhancement
