### ISSUE TITLE
Discovery changes target url to the requesting hostname

### ISSUE THREAD

**Issue by dsg-anthony** [promregator/promregator#119] opened 2019-08-21 15:33 UTC
## Environment
version 0.6.0
CentOS 7
Promregator is running on its own server.

## Summary / Problem Statement
/discovery endpoint behavior changed from version 0.5.7
the targets url changes to the requesters hostname

If I hit the /discovery endpoint with my laptop the target url would be my laptops hostname. In version 0.5.7 this is static to the hostname that is running promregator.

## Observed Behavior
{"targets":["prometheus_hostname:8000"],"labels{..................

## Expected Behavior
{"targets":["promregator_hostname:8000"],"labels{..................

**Comment by eaglerainbow** [comment] 2019-08-21 18:55
Hi,

Welcome at Promregator - and thanks for reporting your issue!

Though I think that I understand the symptom of your issue, I am confused right now. 
From what you write, it appears that you having problems with the line at https://github.com/promregator/promregator/blob/7609d094ac6d4d26417fbcb839f90817de1c7a77/src/main/java/org/cloudfoundry/promregator/endpoint/DiscoveryEndpoint.java#L127 

Promregator's configuration option `promregator.discovery.hostname` (see also [its documentation](
https://github.com/promregator/promregator/blob/7609d094ac6d4d26417fbcb839f90817de1c7a77/docs/config.md#option-promregatordiscoveryhostname-optional)) could be used to overwrite what you want to see as target in your discovery response. However, from what you have written, I would assume that you don't make use of it. The `else` in the triary operator then says that Promregator shall use `request.getLocalName()`, which means that this is the hostname of the "local port where the request was received from the client" -- or how the official API documentation says it:
![grafik](https://user-images.githubusercontent.com/12811079/63459087-4080f180-c454-11e9-9b5a-6b36baad27cd.png)

That is exactly what you want to have. 
Moreover, the coding was not changed since [March 2018](https://github.com/promregator/promregator/blame/master/src/main/java/org/cloudfoundry/promregator/endpoint/DiscoveryEndpoint.java#L127), which is around 0.1.x vs. 0.2.y or so. 
The only difference that would come to my mind would be that Spring (the underlying framework Promregator uses) or the JVM has changed something in its implementation of the call...

Let's stay with the trivial things first:
* Could you please check if you have set `promregator.discovery.hostname` somehow? If yes, what's the value? Does the value change between the two installations?
* What's the laptop's hostname? "prometheus_hostname"? (I have troubles mapping your initial statements properly to each other).

Let's clarify these two things first before we start to dig deeper...

**Comment by eaglerainbow** [comment] 2019-08-21 19:09
I think I was able to reproduce the issue here locally:

The issue is JVM independent: I can reproduce it with the same JVM with Promregator 0.6.0, but not with Promregator 0.5.8-SNAPSHOT.

**Comment by eaglerainbow** [comment] 2019-08-21 19:12
Suggested workaround is to make use of `promregator.discovery.hostname`.

I am trying to still understand what's going wrong here/what has changed.

**Comment by dsg-anthony** [comment] 2019-08-21 19:35
promregator.discovery.hostname is not set in my instance. I will try and test it soon.

When the prometheus server scrapes the /discovery endpoint (CURL job) the json is returned with the prometheus servers hostname in the targets array. when I test it with my laptop the returned json has my laptops hostname in the targets array.

**Comment by eaglerainbow** [comment] 2019-08-21 19:49
I think I found it: it's a bug in Tomcat (utils) - see also https://github.com/apache/tomcat/commit/a6abd652314bfcd53182a2de1a97dde6b910b1b6 and http://mail-archives.apache.org/mod_mbox/tomcat-dev/201907.mbox/%3Cbug-63570-78@https.bz.apache.org/bugzilla/%3E and is apparently fixed with Tomcat 9.0.23 (and later). Promregator currently is using 9.0.22 (only).

**Comment by eaglerainbow** [comment] 2019-08-21 19:50
Tomcat versioning is handled by spring-boot; there is no higher version than 2.1.7 yet.

**Comment by eaglerainbow** [comment] 2019-08-21 19:52
Only option is to manually override the Tomcat version in dependencyManagement.

**Comment by eaglerainbow** [comment] 2019-08-21 19:56
Manual testing worked with enforced dependency injection of Tomcat 9.0.24.

**Comment by eaglerainbow** [comment] 2019-08-21 19:56
New release version is in the making...

**Comment by dsg-anthony** [comment] 2019-08-21 20:07
manually setting promregator.discovery.hostname did work

**Comment by eaglerainbow** [comment] 2019-08-21 20:08
Thanks for the feedback. I hope that there is a fix in a couple of minutes as well...

**Comment by eaglerainbow** [comment] 2019-08-21 20:10
Here we go: fixed with [0.6.1](https://github.com/promregator/promregator/releases/tag/v0.6.1).
The version is already available both for download at github and the docker container at hub.docker.com. The jar version via Maven Central is currently still be distributed and should available within a few hours.

Feedback on testing (then without using `promregator.discovery.hostname`) is appreciated.

**Comment by eaglerainbow** [comment] 2019-08-21 20:10
Thanks again for reporting this!

**Closed by eaglerainbow** 2019-08-21 20:10 UTC
Labels: bug, waiting for release

**Comment by dsg-anthony** [comment] 2019-08-21 20:29
Yes it is now working correctly with and without the promregator.discovery.hostname

Thanks very much! Promregator has been very good to us! 💯

**Comment by eaglerainbow** [comment] 2019-08-21 20:30
Thanks for the feedback once again.

> Promregator has been very good to us!

Appreciated! Tell it to your friends!
