### ISSUE TITLE
Scrape metrics with different auth settings?

### ISSUE THREAD

**Issue by eloo** [promregator/promregator#60] opened 2018-06-07 06:30 UTC
Hi,

as we are working more and more with promregator we have figured out that it is ATM not possible to scrape metrics from apps with different auth settings. For example different basic auth credentials.

what do you think, could this be possible in the future? 
Would be really great for our use-case if we could set different auth settings for specific targets, so maybe configure the default one (like its done now) and optional overwrite it for a single targets?

Does this make sense to you?? :D 

Thanks

**Comment by eaglerainbow** [comment] 2018-06-09 06:46
Your observation is correct. And believe it or not, I had had a thought over that when I was developing it initially. However, I was quite unsure what was the right approach to design it. After all, I had decided to wait for the feature request to come to be able to discuss what the requirement would really look like. 😀 So, here we are now 😝 

The "big solution" would be to go for a declaration of Authentications to prepare, making them identifiable (e.g. `promregator.authenticator` would become an array and each item would have to specify an `id` - or so - mandatorily). This would enable `targets[]` to also specify a `authId`, which then correlates the target to which authenticator to use. The Pros/Cons of this idea are:
* Pro: Easy to understand, as don't have any default/exception logic
* Pro: Arbitrary number of authentications
* Pro: Easy to implement, as `promregator.authenticator` would exactly be the pool of authenticators to choose from.
* Con: hard to generate (for the consumer), as on change of a credential, you might need to split authenticators, you might need to parse the file, if a password changes, ...

The "small solution" is to move the declaration of the authenticator into the targets themselves (get rid of `promregator.authenticator` as a whole):
* Pro: This makes it easy to generate promregator configuration files
* Con: We would  have multiple authenticators, which also may be redundant. Either we have to consolidate them when reading the configuration (which might become a very tricky task, as I have - with conscious decision - introduced the `AuthenticationEnricher` interface, which implies that an authenticator can have any custom configuration setting for its own). 
* Con: Also spreading passwords all over the place of the configuration file doesn't sound to be a good idea from a security's point of view either (not to state here that plaintext passwords are a no-go). 

So, what about a use case discussion here, first? Why do you request this enhancement after all? How do you intend to use it? How many targets do you expect to have? Will some of them share the same set of credentials?

**Comment by eloo** [comment] 2018-06-11 06:34
At the first blink for me the first solution sounds way better.. I would like not to have the same credentials entered multiple times (error prune).

My usecase is that we are having different kinds of services which are secured with different basic auth creds. Further it could may be that we want to have an overall promregator at time to monitor services from different teams, which includes different credentials.

And yes every "group" of services is sharing the same credentials but as explained there will be differents groups ;)

**Comment by dschroe** [comment] 2018-06-11 09:02
As @eloo said, the first solution is the one we should pick. It would be annoying to define the same credentials multiple times.

**Comment by eaglerainbow** [comment] 2018-06-11 18:54
Got your point.
Yet, with #44 we just got a slightly different use case: There you want to authenticate for one target against Promregator itself. What you want there is more like an "exceptional authentication". All the other targets stay the same as before. That's more like a "default **x**, but exception **y**" logic...

**Comment by vervas** [comment] 2018-06-12 14:33
Imho, the second approach sounds more reasonable, since the credentials are really part of a target. This combined with `promregator.targets[].applicationRegex` would also work for the group scenario if a proper naming convention is established, thus preventing from repeating credentials.

**Comment by eaglerainbow** [comment] 2018-06-12 20:20
Ok, now have both positions in place... 😀 
Please feel free to bring up your arguments here and start a discussion. If you also have ideas how to improve the modelling, please feel free to post them here!

**Comment by eloo** [comment] 2018-06-13 06:34
@vervas yes thats a valid point.. but this can also be done using the first approach.
for example by declaring auth credentials in a own point and assign it to an id
afterwards while configuring your targets you are just referring to the credentials id

for example kubernetes is doing something similar with image pull secrets

would this fit to your needs @vervas ?

**Comment by vervas** [comment] 2018-06-13 07:36
Both solutions work, it is more about the right modelling and security.

What kubernetes does with image pull secrets is allowing multiple entities access the same resource, the registry, so this is a scenario of who is authorised to access the *same resource*.

In our case we talk about one entity requesting access to many different resources, which happen to have the *same credentials* (I will not debate wether it makes sense to have many resources configured with the same credentials).

What I am trying to point out is that *same resource* != *same credentials*.

Eventually if you use the same credentials for many targets, you could, as I mentioned, go with the regex pattern, but this means you already followed a naming convention there too. If you haven't then you would either need to rename all your apps or repeat the same credentials (which is also ugly but by no means less secure).

That said both ways work perfectly for me, but from a logical point of view the second feels like a better approach. If that one whatsoever is a whole process for you and the first solution would make your life easier then I'm fine with it too, but keep in mind that using the same credentials for many apps might be a bad idea from the start.

**Comment by eaglerainbow** [comment] 2018-06-16 09:14
Mmmh... The power of both approaches looks similar (if not even equal). So this is more like a question on taste.
What about the following case: You have two sets of applications, which each can be expressed easily in a regex. They both share the same set of credentials (e.g. you are providing a service using Promregator to a third-party, which wants to monitor multiple applications - then you don't want to issue a new set of credentials for each application the third-party generates). However, combining the two regex could become a nightmare (which isn't a big challenge with regex anyway). That's why you want to configure two distinct targets (in the sense of Promregator), but logically they still belong together. Repeating credentials then could be a potential source of error due to the redundancy (you tend to forget to update the second pair of credentials). 

What do you think about that? Valid case or too obscure for you?

**Comment by eaglerainbow** [comment] 2018-06-16 10:08
@vervas As it seems that your opinion about approach two isn't that strictly strong that we would have to enforce it, is it okay, if we make a decision to go for approach one?

**Comment by eloo** [comment] 2018-06-16 12:46
for me both solution would be fine.. so pick what suits you the most :+1:

**Comment by vervas** [comment] 2018-06-19 08:41
Sorry for the late reply. The first solution works as well for me so we can go for it.

**Comment by eaglerainbow** [comment] 2018-06-20 19:17
Ok, then we'll go for option 1. 
I have something in store, but need to turn another round of it on the weekend (that's the first point in time I see a chance for it at least). Moreover, we first need to fix the problem in issue 59, before we may merge something new to the mainline (seems like that there really happened some major glitch over there).

**Comment by eaglerainbow** [comment] 2018-06-23 21:19
With 544fbeb875fe4944eea5e4d968ed4704ecdd6eea and 88d4742f4b8cb1d2b20d337c97d3b62b5cba17d1 I have created some updates on the documentation for this.
Comments on it are welcome!

The stuff will be automatically available with `0.4.0-rc5` and later.

**Comment by vervas** [comment] 2018-06-28 13:01
As mentioned at https://github.com/promregator/promregator/issues/44#issuecomment-401026086 I can confirm that the authenticators at least for basic auth work without a glitch for me.

**Comment by eaglerainbow** [comment] 2018-07-01 20:08
@vervas Thanks for confirming.
@eloo / @dschroe : Any test results from your side on this topic here?

**Comment by eloo** [comment] 2018-07-11 11:10
@eaglerainbow sorry for responding so late but i was on vacation ;)
i will try the new release in time and give feedback asap

**Comment by eaglerainbow** [comment] 2018-07-11 18:44
> sorry for responding so late but i was on vacation ;)

No problem - I hope you had a good one!

**Comment by eaglerainbow** [comment] 2018-07-19 19:52
As already announced in #59: `0.4.0-rc5` is available now and contains this feature here. Please feel free to test thoroughly and provide any kind of feedback.

**Comment by eloo** [comment] 2018-07-20 07:02
okay.. yes i will test it next week 👍

**Comment by eaglerainbow** [comment] 2018-07-24 19:24
As this feature has gone into [v0.4.0](https://github.com/promregator/promregator/releases/tag/v0.4.0), I'd like to consider this topic being finished. Thus, I am closing this issue here.

@eloo: if you tests yield something unexpected, please feel free to open an own issue for that!

**Closed by eaglerainbow** 2018-07-24 19:24 UTC
Labels: author action, enhancement

**Comment by eloo** [comment] 2018-07-25 06:51
@eaglerainbow atm i've not yet tested it due to lack of time..
but i will give feedback when i've tested it
