### ISSUE TITLE
Intermittent "returned multiple web processes via CF API V3 Processes"

### ISSUE THREAD

**Issue by dmarmugi** [promregator/promregator#232] opened 2023-03-16 20:16 UTC
## Environment
Running Promregator v1.0.0, as a jar
CF api version:    3.115.0

## Summary / Problem Statement
In *ReactiveAppInstanceScanner*
Seeing intermittent "... returned multiple web processes via CF API V3 Processes; Promregator does not know how to handle this. Provide your use case to the developers to understand how this shall be handled properly" when fetching `/discovery`

I'm not sure if it's something in how the fluxes are getting assembled, or how the V3 API is responding, but I'm seeing duplicate entries in `final List<ProcessResource> list = lapr.getResources();` This is causing those targets to be dropped. 

## Observed Behavior
Even on apps with a single instance, occasional duplicate resources are reported. These are identical: 
![image](https://user-images.githubusercontent.com/13923591/225741110-d75d15eb-78af-4328-b92e-c28b8b2170aa.png)

![image](https://user-images.githubusercontent.com/13923591/225741051-f5cf221e-8903-4e57-8dfa-32baedb402f9.png)

## Expected Behavior
Only a single resource is returned, or the list is deduplicated prior to processing. Running locally with a change 
```diff
-                       if (list.size() > 1) {
+                       if (list.stream().distinct().toList().size() > 1) {
```
 stopped the issue, but again I don't know if that's masking a bug or covering for the CF API misbehaving.

**Comment by checketts** [comment] 2023-03-16 21:23
I wonder if this is due to a mid-deploy using a `--strategy rolling`.  Do you use rolling deploys?

**Comment by dmarmugi** [comment] 2023-03-17 01:48
> I wonder if this is due to a mid-deploy using a `--strategy rolling`. Do you use rolling deploys?

No, not at the moment.

**Comment by dmarmugi** [comment] 2023-03-17 19:02
Sorry, I know there's not enough in here to repro. If I get time I'll try and dig into it more

**Comment by eaglerainbow** [comment] 2023-03-17 19:06
First of all: Many thanks for reporting this!
I would love to dig a little more into it - but for that I also first need to analyze what might be possible candiates.

@checketts Thanks for ruling out rolling-updates already.

> Sorry, I know there's not enough in here to repro. If I get time I'll try and dig into it more

Got it. 
I'll try to wrap my head around it with the intention that can post you some things here, which would allow us analyze it better/more efficient.
For me the most important thing would be: How easy it is to reproduce this case in first place? Is this a 100% hit - or also happening only sporadic for you?

**Comment by eaglerainbow** [comment] 2023-03-18 08:01
<thinkingAloud>
The `list.get(0).equals(list.get(1))` is telling us rather a lot. Given that the generator with the input of 
https://github.com/cloudfoundry/cf-java-client/blob/v5.9.0.RELEASE/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/processes/_ProcessResource.java

creates the following snippet:
```java

@Generated(from = "_ProcessResource", generator = "Immutables")
@SuppressWarnings({"all"})
@javax.annotation.Generated("org.immutables.processor.ProxyProcessor")
public final class ProcessResource extends org.cloudfoundry.client.v3.processes._ProcessResource {
  /**
   * This instance is equal to all instances of {@code ProcessResource} that have equal attribute values.
   * @return {@code true} if {@code this} is equal to {@code another} instance
   */
  @Override
  public boolean equals(Object another) {
    if (this == another) return true;
    return another instanceof ProcessResource
        && equalTo((ProcessResource) another);
  }

  private boolean equalTo(ProcessResource another) {
    return createdAt.equals(another.createdAt)
        && id.equals(another.id)
        && links.equals(another.links)
        && Objects.equals(updatedAt, another.updatedAt)
        && command.equals(another.command)
        && diskInMb.equals(another.diskInMb)
        && healthCheck.equals(another.healthCheck)
        && instances.equals(another.instances)
        && memoryInMb.equals(another.memoryInMb)
        && metadata.equals(another.metadata)
        && relationships.equals(another.relationships)
        && type.equals(another.type);
  }
```
it means that we don't just have a matching `id`, but also the `createdAt`, `updatedAt`, `metadata` and `relationships` information is the same.

Note thought, that the second screenshot states that the two instances of `ProcessResource` are distinct, i.e. they have different Java object instance identifiers (14292 vs. 14923), i.e. they are two separate objects on JVM's heap (and not, for example the same object added to the same list twice). 

This makes 

https://github.com/promregator/promregator/blob/7c0fd0dbc3cd1ffcecf420787c51cd88ec2c4df8/src/main/java/org/cloudfoundry/promregator/scanner/ReactiveAppInstanceScanner.java#L222

suspicious.

I tried to execute the scenario on my local machine (against my ol' bluemix installation) and I could not reproduce it on the first, simple shot. So, it's nothing "obvious and trivial".

Due to https://github.com/promregator/promregator/blob/7c0fd0dbc3cd1ffcecf420787c51cd88ec2c4df8/src/main/java/org/cloudfoundry/promregator/cfaccessor/ReactiveCFPaginatedRequestFetcher.java#L331 we currently cannot say, whether this issue is due to a paging problem (e.g. ` page.getPagination().getTotalPages()` could have returned a wrong value of `2`) or whether the two instances really were emitted (in the same page) by the CFCC.

Thanks to metric `promregator_cffetch_latency_count` with `label = processes`, however, we could determine on how many pages were read, if we look at the value before and after such an occurrence.

One more word at 
```diff
-                       if (list.size() > 1) {
+                       if (list.stream().distinct().toList().size() > 1) {
```

That's not the right place - it would just silence the warning message - but still the subsequent logic would get out of sync (stopping there, has certain reason 😄). In case we really come to the conclusion that we need to "fix the issue by filtering on the client side", it would be better to calculate the distinct set somewhere around https://github.com/promregator/promregator/blob/7c0fd0dbc3cd1ffcecf420787c51cd88ec2c4df8/src/main/java/org/cloudfoundry/promregator/cfaccessor/ReactiveCFPaginatedRequestFetcher.java#L334 -- either by `.stream().distinct()` or via `HashSet`ing it. 
</thinkingAloud>

**Comment by eaglerainbow** [comment] 2023-03-18 08:33
@dmarmugi Please try to following:

1. Make sure that you have set `promregator.metrics.internal: true`.
2. Make sure that you are using Promregator 1.0.1 or higher (necessary due to #233)
3. Make sure that the configuration of your scenario only contains a single target application (you may use wildcards in your config, but these may only hit exactly one application).
4. Start Promregator in your original scenario.
5. Fetch the PromregatorMetrics, e.g. by calling `curl -H 'Accept: application/openmetrics-text; version=1.0.0; charset=utf-8' http://localhost:8080/promregatorMetrics` and filter for `promregator_cffetch_latency_seconds_count{request_type="processes_singlePage"}`. In case you don't find that metric, assume its value to be zero. Take this value as baseline.
6. Trigger the discovery and reproduce this case on the first shot. If you can't reproduce it on the first shot, you must create a new baseline (as described in the step before) before trying again.
7. Having reproduce it, fetch the metric for `promregator_cffetch_latency_seconds_count{request_type="processes_singlePage"}` again. Take the difference between your baseline value and the last value. It should either be 1 or 2. Which one is it?

(PS: Release of 1.0.1 to happen soon).

**Comment by eaglerainbow** [comment] 2023-03-18 10:41
Promregator [1.0.1 is released](https://github.com/promregator/promregator/releases/tag/v1.0.1).

**Comment by eaglerainbow** [comment] 2023-03-24 23:24
Any update on this?

**Comment by braunsonm** [comment] 2023-08-23 20:59
@eaglerainbow We are also experiencing this issue. Do you still need a test dummy or was this fixed in a later version?

**Comment by eaglerainbow** [comment] 2023-08-23 21:13
> @eaglerainbow We are also experiencing this issue. Do you still need a test dummy or was this fixed in a later version?

@braunsonm 
From my perspective, we are still in analysis for this case. I don't think that it is fixed.
So, if you could create a reproducible case where we can learn from, then this could be very helpful.

**Comment by braunsonm** [comment] 2023-08-23 21:33
Because of the intermittent nature of this as stated by @dmarmugi I don't have a way to reproduce this yet.

It looks like he has forked this and added a distinct call which might be helping. Do you want me to get that metric you asked for in your previous replies? Is that still useful to know what CAPI is returning?

While this issue occurs (can last from 1-4 hours) all metrics from our apps are unable to be collected.

**Comment by eaglerainbow** [comment] 2023-08-24 06:36
> Because of the intermittent nature of this as stated by @dmarmugi I don't have a way to reproduce this yet.

Okay, how often do you experience it? e.g. Every day, once a week or month?

> It looks like he has forked this and added a distinct call which might be helping. Do you want me to get that metric you asked for in your previous replies? Is that still useful to know what CAPI is returning?

Essentially, that's what we need: I need to understand what CAPI returns. If we got that, I ran wrap me head around it how to determine the "right" web process from the list.
Otherwise, if we just let the error slip through, it's we may cause all kind of inconsistencies. That's also why I am cautious with @dmarmugi's workaround. 

> While this issue occurs (can last from 1-4 hours) all metrics from our apps are unable to be collected.

Oh, that's very long. 
But yeah, given the severity of what happens there, I am not surprised: Promregator simply doesn't expect this case to happen. There is also little alternatives to fall back more gracefully, because Promregator can't really know what scope is affected.
I can try to wrap my head around it to make it fail more gracefully, but I have little hopes there...

**Comment by braunsonm** [comment] 2023-08-29 13:56
@eaglerainbow The metric goes up by 2 when the problem occurs. Is there any work around you would suggest?

**Comment by eaglerainbow** [comment] 2023-08-29 19:13
> @eaglerainbow The metric goes up by 2 when the problem occurs. 

Just to be 100% sure, because it is rather out of context: You are talking about metric `promregator_cffetch_latency_seconds_count{request_type="processes_singlePage"}`, right?

> Is there any work around you would suggest?

If my assumption above holds true, I wouldn't see any workaround so far. I think, the only possible option would be some sort of coding change - but I am still a little unsure what would be "the right coding change". Only "distinct" sounds rather bold to me...

Let's first clarify that we talk about the same thing - then I'll try to wrap my head around it...

**Comment by braunsonm** [comment] 2023-08-29 19:51
Yes, that's the metric I'm talking about.

**Comment by eaglerainbow** [comment] 2023-08-30 06:47
Over night I perhaps got some idea: 

Due to https://github.com/promregator/promregator/blob/373bd54a7cd495fa8638f2687f371cc070d6691c/src/main/java/org/cloudfoundry/promregator/cfaccessor/CFAccessorCacheCaffeine.java#L474 it may be worthwhile to try calling endpoint `/cache/invalidate` with `?process=true` set (see also https://github.com/promregator/promregator/blob/373bd54a7cd495fa8638f2687f371cc070d6691c/docs/invalidate-cache.md#cache-invalidation-via-http-rest-endpoint) as soon as this strange "hung state" is reached. Promregator then might recover from the hung state.
If that worked, also playing around with `cf.cache.expiry.process` (i. e. lowering it to something like 2-3 seconds or so - don't go below that) might help to mitigate it a little.

@braunsonm Is it possible for you to try this out?

However, it's clear that this is no final solution then... it's just a mitigation...

**Comment by eaglerainbow** [comment] 2023-08-30 18:27
> I also am messing around with the cf CLI cf curl /v3/apps/<GUID>/processes?types=web only returns a single web resource (with multiple instances). So I'm not sure where Promregator is getting this from or if it's intermittent.

That's an interesting aspect.

> I could try playing with the expiry.process if you think it would still help?

Nah. Given that `/cache/invalidate` doesn't move the thing, I can't imagine that `expiry.process` will be of help either.

Given all that - and that we are still guessing around here - I am currently preparing a 1.1.x-rc* version, which would add a debugging probe. From that I hope to get a lot of more clarity.

@braunsonm Would you be willing to send me the output of the debugging probe (if necessary [via encrypted direct email](https://github.com/promregator/promregator/blob/7d3bab6423aa83bc2aec4438cf5f7c75bee0ece4/docs/analysis-material.md) in case you fear to expose some internal information which wasn't supposed for public eyes)? Perhaps we then get a catch on what's going on here...

**Comment by braunsonm** [comment] 2023-08-30 18:39
@eaglerainbow I deleted my reply because I wanted to try the cache eviction again the next time it happened. I might have been mistaken. I've been waiting today for the problem to occur but I haven't been able to catch it live yet.

Unfortunately I will not be able to provide any logs - regardless of the encrypted nature. I can do my best to tell you the output in a censored context though

**Comment by eaglerainbow** [comment] 2023-08-30 18:42
> I deleted my reply because [...]

Sorry, hadn't seen this - I used the cached github.com browser 😀 

> Unfortunately I will not be able to provide any logs - regardless of the encrypted nature. I can do my best to tell you the output in a censored context though

Fair deal. 
I'll try to get the rc-version released - and once it happened again, please store the logs locally. We then will play ping-pong until I get the necessary structural information.

**Comment by eaglerainbow** [comment] 2023-08-30 18:58
Here we go: [1.1.1-rc1](https://github.com/promregator/promregator/releases/tag/v1.1.1-rc1).

Please ping me here once ready.
(Note: I'll be on tour almost the entire Thursday and Friday. If applicable, please expect a corresponding delay)

**Comment by braunsonm** [comment] 2023-08-30 19:39
So I'm running this right now and already can see the problem. Every application has a list size of 2, the two processes that you log are completely identical. Same IDs and everything. I put the two lines into a diff checking tool to confirm.

What I'm unsure of is if Promregator is adding a duplicate, or if the CF API is actually returning duplicates. I still cannot reproduce it with `cf curl`.

**Comment by eaglerainbow** [comment] 2023-08-30 19:48
> So I'm running this right now and already can see the problem. Every application has a list size of 2, the two processes that you log are completely identical. Same IDs and everything. I put the two lines into a diff checking tool to confirm.

That's interesting, but also sounds logical as it would explain why @dmarmugi's quickfix using `distinct()` did the trick.

> What I'm unsure of is if Promregator is adding a duplicate, or if the CF API is actually returning duplicates. I still cannot reproduce it with cf curl

I think we should take this as a sign that Promregator is likely the culprit. I will dig into this, hoping to detect something through code reading. If things come to worse, we might need another debugging probe (and hence a new rc version) to help is narrowing down things further.
I'll get back to you.

**Comment by eaglerainbow** [comment] 2023-08-30 20:02
I have a suspicion: If we have a process cache miss and two Promregator threads manage to request the process information for the same appid within 125ms, then we will have the same item (appid) twice in the `RequestAggregator`'s block at https://github.com/promregator/promregator/blob/10a2df4c529af6ac65072a08d2ff3b40ace97901/src/main/java/org/cloudfoundry/promregator/cfaccessor/RequestAggregator.java#L77
As the postprocessing of the result is written well-enough to cater for multiple items to come back (collision list with multivalue approach, see also https://github.com/promregator/promregator/blob/10a2df4c529af6ac65072a08d2ff3b40ace97901/src/main/java/org/cloudfoundry/promregator/cfaccessor/CFAccessorCacheCaffeine.java#L261), we would also pass these duplicates through to https://github.com/promregator/promregator/blob/10a2df4c529af6ac65072a08d2ff3b40ace97901/src/main/java/org/cloudfoundry/promregator/scanner/ReactiveAppInstanceScanner.java#L230

**Comment by eaglerainbow** [comment] 2023-08-30 20:19
If my statement above holds true, the probability of failure may be reduced by setting Promregator's configuration option `cf.cache.aggregator.checkinterval.process` to a lower value (default 125). However, setting it too low may cause unnecessary high CPU usage (burning CPU cycles totally in vain). I would not go lower than 5.
That's something which you, @braunsonm, might be able to check. However, this would only be a mitigation and does not rule out the problem entirely. 

There is one more thing which might be helpful. I don't know how much traffic you have on Promregator, but setting

```
logging.level.org.cloudfoundry.promregator.cfaccessor.RequestAggregator=DEBUG
``` 

could give us some further hints. If Promregator is too loaded, then you will be flooded with (mainly useless) log statements.
What I am essentially after is the logging at

https://github.com/promregator/promregator/blob/10a2df4c529af6ac65072a08d2ff3b40ace97901/src/main/java/org/cloudfoundry/promregator/cfaccessor/RequestAggregator.java#L74

If you are lucky, you might catch another case and then I would expect to see a logging of 

```
Woke up with 2 items in the queue
```
for a thread called `Processor for ReactiveCFAccesor requests String -> ListProcessesResponse` shortly before Promregator hangs up. If that held true, we had another rather good hint into the direction of my suspicion above.
However, be careful with combining this together with low values of `cf.cache.aggregator.checkinterval.process` - you might regret it, if Promregator is under full load (vast load of log statements can be generated, which are too fast for any logging facility to keep up with).

**Comment by eaglerainbow** [comment] 2023-08-30 20:30
Too bad, the suspicion does not hold true:
Because of the HashSet conversion at https://github.com/promregator/promregator/blob/10a2df4c529af6ac65072a08d2ff3b40ace97901/src/main/java/org/cloudfoundry/promregator/cfaccessor/CFAccessorCacheCaffeine.java#L247C55-L247C55 duplicates would already have been eliminated.
This suggests that we can simplify the coding, but we don't have a valid case any longer. 😢

**Comment by braunsonm** [comment] 2023-08-31 12:55
hm. I suppose adjusting that value would no longer be useful then?

**Comment by eaglerainbow** [comment] 2023-09-02 09:03
> hm. I suppose adjusting that value would no longer be useful then?

Yeah, unfortunately. Playing around with `cf.cache.aggregator.checkinterval.process` after the insight above most likely won't help. 
I will wrap my head around this for another round now. Will keep you posted here.

**Comment by eaglerainbow** [comment] 2023-09-02 10:17
Observation: https://v3-apidocs.cloudfoundry.org/version/3.145.0/index.html#the-process-object mentions the `version` attribute to exist, but https://github.com/cloudfoundry/cf-java-client/blob/e92f3a5de50eda42b458134cbac559ed645d9a02/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/processes/Process.java#L26 misses this attribute.
So, our `toString()` methods there will report incomplete data: The objects "appear to the consumer" to be duplicates, but in fact are not (due to incomplete mapping).

**Comment by eaglerainbow** [comment] 2023-09-02 10:29
@braunsonm What's your CAPI V3 version?
You may find that out by looking at
```
curl https://<api.url>/
```

and there looking at the attribute at `links.cloud_controller_v3.meta.version`.
The question is whether you are `>3.141.0` or not.

**Comment by eaglerainbow** [comment] 2023-09-02 11:41
I just made [1.1.1-rc2](https://github.com/promregator/promregator/releases/tag/v1.1.1-rc2). Essentially, the new version only contains four new debugging probes:

* https://github.com/promregator/promregator/blob/9d490280cbb0e5b01bb97e3e119b66b3ca300a29/src/main/java/org/cloudfoundry/promregator/cfaccessor/ReactiveCFAccessorImpl.java#L372
* https://github.com/promregator/promregator/blob/9d490280cbb0e5b01bb97e3e119b66b3ca300a29/src/main/java/org/cloudfoundry/promregator/cfaccessor/ReactiveCFAccessorImpl.java#L386
* https://github.com/promregator/promregator/blob/9d490280cbb0e5b01bb97e3e119b66b3ca300a29/src/main/java/org/cloudfoundry/promregator/cfaccessor/ReactiveCFAccessorImpl.java#L409
* https://github.com/promregator/promregator/blob/9d490280cbb0e5b01bb97e3e119b66b3ca300a29/src/main/java/org/cloudfoundry/promregator/cfaccessor/ReactiveCFAccessorImpl.java#L424

I would expect that only the last two really matter.
The idea with these debugging probes are that we may determine, whether Promregator is somehow duplicating them or we already get the duplicates in from CF. Having seen https://github.com/promregator/promregator/issues/232#issuecomment-1703789711, I am currently more guessing the latter.

@braunsonm Please give it a try. 
Please note that you will need to have `logging.level.org.cloudfoundry.promregator.cfaccessor.ReactiveCFAccessorImpl` (or one of the parent loggers) have set to `DEBUG`. Otherwise the debugging probes will not do anything.

**Comment by braunsonm** [comment] 2023-09-15 18:58
Sorry @eaglerainbow not sure how I missed these. I will test this RC out next week and report back!

**Comment by eaglerainbow** [comment] 2023-09-15 19:13
@braunsonm all good :) Thanks for checking!

Note: I'll be off (for vacation) starting on Sept 19th. So, I might not be available for a couple of days (don't know yet, how often I can get to PC there - I try to digital-detox a little 😄 )...

**Comment by braunsonm** [comment] 2023-09-20 20:06
Got this deployed here's some interesting bits:

```
Received process page in requestFunction with 50 items
Duplicate entries detected in responseGenerator: true
Received process page in responseGenerator with 100 items - total number of pages: 2
...
Adding item <UUID>
Resolving <UUID> with null
Resolving <UUID> with ListProcessesResponse{...}
```

The controller version is `3.137.0` @eaglerainbow

**Comment by eaglerainbow** [comment] 2023-09-22 06:04
> Got this deployed here's some interesting bits:
> 
> ```
> Duplicate entries detected in requestFunction: false
> Received process page in requestFunction with 50 items
> Duplicate entries detected in responseGenerator: true
> Received process page in responseGenerator with 100 items - total number of pages: 2
> ...
> Adding item <UUID>
> Resolving <UUID> with null
> Resolving <UUID> with ListProcessesResponse{...}
> ```
> 
> The controller version is `3.137.0` @eaglerainbow Last two lines seem to alternate periodically

:fire: 💩 🔥 
If I get this right, this means that the duplication comes from Promregator internally.
I am on vacation, so I am not at my usual infrastructure; still I'll try to wrap my head around this again.
The good thing is: If I am not mistaken above, then there should be a fix which Promregator can deploy alone.
I'll get back to you.

**Comment by eaglerainbow** [comment] 2023-09-22 09:17
I *think* I found the issue. As usual, it's something trivial (see also 12e0555): The paging mechanism was flawed. As long as we did not request more than 50 applications for their processes, everything went fine. As soon as we had the 51st application in progress simultaneously, a second page was necessary. Due to the paging flaw, the second page will contain the same data as the first one: that's where we got the duplicates from. Even worse, the data for the applications, which should have been returned on the second page, will get missed. Most likely, this would mean that for those applications, no data will be scraped (because no process information is available).
This also means that @dmarmugi's [initial proposal](https://github.com/promregator/promregator/issues/232#issue-1628204294) for a fix is only a workaround to mitigate the effect - but will have unwanted side-effects (i.e. not solving the root cause of the issue). 
Moreover, the same structural flaw also existed for retrieving routes. However, as the packages there are much smaller, most likely we haven't encountered any issues with that yet by chance. Still I fixed that as well using the same commit.

As I am currently not at home, I do not have my usual test environment with me, so that I corrected the issue shooting a little into the blue.
Still I have created [another release candidate (1.1.1-rc3)[https://github.com/promregator/promregator/releases/tag/v1.1.1-rc3].
@braunsonm Could you give it a try in your environment? Please consider it "even more" test-like than usual: I could not run that version through several tests, which I usually do.

Looking forward to your feedback!

**Comment by braunsonm** [comment] 2023-09-25 14:32
Good news @eaglerainbow this fix looks like it's working! I'll leave it running for the next few days and check back if the error comes back but looks promising. Thanks for your tenacity on this!

**Comment by eaglerainbow** [comment] 2023-09-25 16:50
Indeed, that's good news!

>  I'll leave it running for the next few days and check back if the error comes back [...]

Sounds like a good plan. I'll be back towards this weekend again.
If, by then, you haven't encountered any failure, I would run the current state through the usual testsuite and release a new patch version (then most probably becoming 1.1.1).

> Thanks for your tenacity on this!

Thanks for *your* tenacity on this bug, providing me the suitable environment to remote-debug it! I couldn't have found the issue myself, because none of my environments would have had enough applications for triggering the case.

**Comment by eaglerainbow** [comment] 2023-09-25 17:08
Note to myself: prior to 1.1.1 release, the debugging probes need to be removed again.

**Comment by eaglerainbow** [comment] 2023-09-30 11:31
just fwiw: I am back, but when I tried to release 1.1.1, I only came through partially: I ran into some (to promregator unrelated) issue with my integration test landscape (CF). That's why 1.1.1 is a "half-broken" release and should not be used (does not differ to 1.1.1-rc3 anyway). 
I need to fix my test landscape first before I can do a proper release.

@braunsonm Have your tests shown any further issue, which should prevent a new release (assuming that my landscape was okay again)?

**Comment by braunsonm** [comment] 2023-09-30 15:28
So far it's been fine!

**Comment by eaglerainbow** [comment] 2023-09-30 21:09
After a lot of challenges (not just the landscape infrastructure was troublesome, but also OSSRH had a very bad day) I was able to release [1.1.3](https://github.com/promregator/promregator/releases/tag/v1.1.3) now. Essentially, it's the same thing as 1.1.1-rc3, but this time all tests I usually run through also went through successfully.
Version 1.1.1 and 1.1.2 are dead bodies because of the OSSRH issue. Simply ignore/skip them and directly go to 1.1.3...

**Comment by eaglerainbow** [comment] 2023-09-30 21:10
Given the positive statement at https://github.com/promregator/promregator/issues/232#issuecomment-1741790344, I dare to close this issue here.
In case of anything still coming up in this case, please feel free to mention it here - then we can reopen it right away.

**Closed by eaglerainbow** 2023-09-30 21:10 UTC
Labels: bug, waiting for release
